In [1]:
import torch
import matplotlib.pyplot as plt

In [2]:
def describe_tensor(t):
    """
    Describes a few basic elements about any torch.Tensor.
    Prints out shape, number of elements, and rank.
    """
    print(f"Shape (Tensor.shape): {t.shape}")
    print(f"Number of elements (Tensor.numel()): {t.numel()}")
    print(f"Number of dimensions, or rank + 1 (Tensor.ndim): {t.ndim}")
    print(f"Tensor type (Tensor.dtype): {t.dtype}")

In [3]:
rank0tensor = torch.tensor(1)
rank0tensor

tensor(1)

In [4]:
describe_tensor(rank0tensor)

Shape (Tensor.shape): torch.Size([])
Number of elements (Tensor.numel()): 1
Number of dimensions, or rank + 1 (Tensor.ndim): 0
Tensor type (Tensor.dtype): torch.int64


In [5]:
rank1tensor = torch.tensor([1.,2,3])
rank1tensor

tensor([1., 2., 3.])

In [6]:
describe_tensor(rank1tensor)

Shape (Tensor.shape): torch.Size([3])
Number of elements (Tensor.numel()): 3
Number of dimensions, or rank + 1 (Tensor.ndim): 1
Tensor type (Tensor.dtype): torch.float32


In [7]:
rank2tensor = torch.tensor(
    [
     [1.,2,3],
     [4,5,6],
     [7,8,9]
    ]
)
rank2tensor

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [8]:
describe_tensor(rank2tensor)

Shape (Tensor.shape): torch.Size([3, 3])
Number of elements (Tensor.numel()): 9
Number of dimensions, or rank + 1 (Tensor.ndim): 2
Tensor type (Tensor.dtype): torch.float32


In [9]:
rank3tensor = torch.rand(3, 3, 3)
rank3tensor

tensor([[[0.0712, 0.1409, 0.4864],
         [0.1888, 0.7116, 0.2082],
         [0.5569, 0.7603, 0.6068]],

        [[0.4351, 0.6399, 0.9933],
         [0.8454, 0.4870, 0.2509],
         [0.9519, 0.7376, 0.7208]],

        [[0.7316, 0.9466, 0.5627],
         [0.5643, 0.9673, 0.9188],
         [0.9194, 0.2633, 0.9670]]])

In [10]:
describe_tensor(rank3tensor)

Shape (Tensor.shape): torch.Size([3, 3, 3])
Number of elements (Tensor.numel()): 27
Number of dimensions, or rank + 1 (Tensor.ndim): 3
Tensor type (Tensor.dtype): torch.float32


In [11]:
# We won't try to visualize this tensor since it doesn't fit neatly into my brain.
# This is just to show we can make big tensors, even if we don't have a practical use for them.
n_dim = 10
describe_tensor(torch.randn(*(tuple([3] * n_dim))))

Shape (Tensor.shape): torch.Size([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])
Number of elements (Tensor.numel()): 59049
Number of dimensions, or rank + 1 (Tensor.ndim): 10
Tensor type (Tensor.dtype): torch.float32


# Exercise 3.1: Torch `dtype`s

Read through the [documentation](https://pytorch.org/docs/stable/tensor_attributes.html#torch-dtype) on different tensor types.

Create a function that uses the [`Tensor.element_size()`](https://pytorch.org/docs/stable/generated/torch.Tensor.element_size.html#) and `Tensor.numel()` methods to calculate the memory footprint of a tensor in megabytes.
There are 1e6 bytes in a megabyte.
Then, create at least 3 tensors with the same shape but different `dtype`s like `torch.float16` and `torch.float32`.
What's the difference in the memory footprints of the following tensors?

<!-- startquestion -->


In [22]:
def memory_footprint(tensor):
    mb = tensor.element_size() * tensor.numel() / 1e6
    return mb
    raise NotImplementedError('Implement this function!')

In [23]:
tensors = [
    torch.tensor(100, dtype=torch.float16),
    torch.tensor(100, dtype=torch.float32),
    torch.tensor(100, dtype=torch.int32),
    torch.tensor(100, dtype=torch.long) # I think this is int64
]

for t in tensors:
    print(f"""
    Tensor:
    {t}
    dtype: {t.dtype}
    memory footprint (MB): {memory_footprint(t)}
    ----------------
    """)


    Tensor:
    100.0
    dtype: torch.float16
    memory footprint (MB): 2e-06
    ----------------
    

    Tensor:
    100.0
    dtype: torch.float32
    memory footprint (MB): 4e-06
    ----------------
    

    Tensor:
    100
    dtype: torch.int32
    memory footprint (MB): 4e-06
    ----------------
    

    Tensor:
    100
    dtype: torch.int64
    memory footprint (MB): 8e-06
    ----------------
    


In [24]:
x = torch.ones(4).float()
x

tensor([1., 1., 1., 1.])

In [25]:
x * 4

tensor([4., 4., 4., 4.])

In [26]:
x + 4

tensor([5., 5., 5., 5.])

In [27]:
x - 2

tensor([-1., -1., -1., -1.])

In [28]:
x / 4

tensor([0.2500, 0.2500, 0.2500, 0.2500])

In [29]:
x = torch.rand(2,2)
y = torch.rand(2,2)
x, y

(tensor([[0.5664, 0.8655],
         [0.8023, 0.8976]]),
 tensor([[0.7836, 0.4461],
         [0.9562, 0.3156]]))

In [ ]:
x + y

In [ ]:
x - y

In [ ]:
x * y

In [ ]:
x / y

In [ ]:
x = torch.rand(2, 4)
y = torch.rand(4)
x, y

In [ ]:
torch.stack([x[0] * y, x[1] * y])

In [ ]:
x * y

In [ ]:
x = torch.rand(3, 2, 4)
x

In [ ]:
torch.stack([torch.stack([i * y for i in a]) for a in x])

In [ ]:
x * y

In [ ]:
x = torch.tensor([1, 2, 3, 4])
y = torch.tensor([2, 3, 4, 5])

In [ ]:
# Let's do this using element-wise operations
(x * y).sum()

In [ ]:
# torch.matmul does matrix multiplication.
torch.matmul(x, y)

In [ ]:
# @ is shorthand for matrix multiplication as well.
x@y

In [ ]:
y@x

In [ ]:
assert x@y == y@x == torch.matmul(x,y) == (x * y).sum()

In [ ]:
X = torch.tensor([[1, 2], [3, 4]])
Y = torch.tensor([[2, 3, 4], [5, 6, 7]])

In [ ]:
X@Y

In [ ]:
(torch.randn(16, 3, 3, 3) @ torch.randn(3, 3, 12)).shape

# Exercise 3.2: matrix multiplication

Previously, we tried to multiply `X@Y`.
Will `Y@X` work?
Why or why not?

In the cell below, define `B`  using `torch.rand` so that `A@B` returns a tensor with shape (4, 7).

<!-- startquestion -->

In [ ]:
A = torch.rand(4, 2)
B = ...

In [ ]:
if not isinstance(B, type(...)):
    assert (A@B).shape == (4, 7)
else:
    print('Please define B such that (A@B).shape = (4, 7)')

In [ ]:
X = torch.tensor(list(range(27))).reshape(3,3,3)
X

In [ ]:
X.sum()

In [ ]:
# Change the dim parameter to see how the results change
X.sum(dim=0)

In [ ]:
# Create a vector
X = torch.arange(0, 3*3*3)
X

In [ ]:
# Reshape it into a 3x3x3 to be "image-like"
X = X.reshape(3, 3, 3)
X

In [ ]:
# How do we add a "batch_dim"?
# Unsqueeze addes an empty dimension
# Squeeze takes away empty dimensions
X.shape, X.unsqueeze(0).shape

In [ ]:
# Use unsqueeze to create a "batch"
torch.cat([X.unsqueeze(0), X.unsqueeze(0)]).shape

In [ ]:
y = torch.randn(1, 1, 1, 1, 1, 1, 8)
y, y.shape, y.squeeze(), y.squeeze().shape, y.squeeze(2).shape

In [ ]:
# squeeze and unsqueeze are opposites
assert X.shape == X.unsqueeze(0).squeeze(0).shape

In [ ]:
# Swap the 1nd and 2rd dim
X.permute(0, 2, 1)

# Exercise 3.3: Write your own `sigmoid` function

The `softmax` function is given.
Use a similar approach to complete the `sigmoid` function.
$e^x$ in `torch` is expressed using `torch.exp(x)`.

<!-- startquestion -->

In [ ]:
def sigmoid(x):
    raise NotImplementedError()

def softmax(x, dim):
    raise NotImplementedError()

In [ ]:
x = torch.arange(-8, 8, 0.05)
plt.plot(x, sigmoid(x), label='our sigmoid', ls='--', color='r', linewidth=4)
plt.plot(x, torch.sigmoid(x), label='torch sigmoid', c='b', alpha=0.8)
plt.legend()

In [ ]:
X = torch.rand(3, 3)
print(
    'X:', X,
    'Our softmax(x):', softmax(X, dim=0),
    'Torch softmax(x):', torch.softmax(X, dim=0),
    'Sanity check: row sums:', softmax(X, dim=0).sum(dim=0),
    sep='\n'
)

In [ ]:
# We can also call softmax on a tensor
X.softmax(dim=0)

In [ ]:
(torch.randn(16, 3, 4) * torch.randn(3, 4)).shape

In [ ]:
(torch.randn(16, 3, 4) @ torch.randn(3, 4)).shape

In [ ]:
(torch.randn(16, 3, 4) @ torch.randn(4, 7)).shape

In [ ]:
torch.randn(3, 4) * torch.randn(4, 3)

In [ ]:
torch.randn(3, 4) @ torch.randn(4, 3)